kubevirt/kubevirt.github.io

about.md, index.md
This PR uses content that we collaboratively came up with during the f2f meetings.
=> Provide updated content about the project aims & motivation

use-cases.md
Fix a tiny typo.
Signed-off-by: Arik Hadas <ahadas@redhat.com>
=> fix typo: ect -> etc

about.md
Really minor fixes.
Signed-off-by: Arik Hadas <ahadas@redhat.com>
=> Minor fixes in the motivation page.

contrib-workflow.md, contrib.md, css/main.scss, docs.md
This page describes use of the issue tracker, commit sign off,
design docs and pull requests.
=> Add doc describing how to contribute to project GIT repositories

docs.md
Add a link to the User Guide to the Docs page.
=> Add link to User Guide

_posts/2018-05-08-kubevirt-objects.markdown
Let's try this agian ;-)
@fabiand and @scollier here is an updated version from the feedback given. This
hasn't been re-reviewed but the content is mostly the same.
=> Kubevirt Objects post

_posts/2018-05-16-KubeVirt-API-Access-Control.markdown
blog post outlining how access control and RBAC roles work in KubeVirt
=> kubevirt access control post

_posts/2017-11-25-This-Week-in-Kube-Virt-12.markdown, _posts/2018-04-27-This-Week-in-Kube-Virt-23.markdown, _sass/_layout.scss, index.html, pages/blog.html, pages/get_kubevirt.md
Changing the way the blog preview are shown - caused an html breaking
Minor css changes
Show preview of blog in homepage
=> Working on blogs

_config.yml, _data/site_nav_pages.yml, _includes/header.html, _includes/paging.html, _layouts/post.html, pages/blog.html
Trying to fix problem of blog post that breaks the HTML.
I'm a bit blind here since in Eldan's setup it works fine.
E
=> blog preview html break - fix

_config.yml, pages/get_kubevirt.md
Signed-off-by: karmab <karimboumedhel@gmail.com>
=> update version in get started page and make it dynamic

_posts/2018-06-07-Non-Dockerized-Build.markdown, assets/2018-06-07-Non-Dockerized-Build/Makefile.nocontainer, assets/2018-06-07-Non-Dockerized-Build/copy-cmd.sh
this is a blog post regarding non-dockerized build
=> Non dockerized build

pages/get_kubevirt.md
This was the one area where got tripped up while installing minikube and running kubevirt on my laptop.
=> Update minikube install - add check for KVM nested virtulization

_posts/2018-06-20-KVM-Using-Device-Plugins.markdown
Signed-off-by: Stu Gott <stu-gott@users.noreply.github.com>
=> Blog post about KubeVirt and Device Plugins

_posts/2018-06-03-Research-run-VMs-with-istio-service-mesh.markdown, _posts/2018-06-13-Proxy-vm-conclusion.markdown
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt.github.io/55)
=> Blog about proxy conclusion

pages/community.md
Fix Kubernetes Architecture link
=> Fix Kubernetes Architecture link

_sass/_buttons.scss, _sass/_hero.scss, _sass/_layout.scss
This PR updates the various layouts for mobile view that did not fit/flow properly.
=> fix(layouts): updates layouts for mobile

_config.yml, _posts/2018-06-20-Hello-KubeVirt-on-Minikube.markdown
This is pretty much exactly what I did to get Kubevirt running on my workstation.  I hope others find it useful!
=> Blog post about installing Minikube and KubeVirt on Fedora 28

_config.yml
=> KubeVirt version bump

_config.yml, _includes/footer.html, _sass/_buttons.scss, pages/community.html
This PR updates the Community page to fix incorrect links, add a calendar link, and adjust button alignment on mobile view.
=> fix(community): update community page

_includes/head.html, pages/qe-tools.md
Fixes: kubevirt/qe-tools#10
Signed-off-by: Lukas Bednar <lbednar@redhat.com>
=> Adds go get kubevirt.io/qe-tools support

pages/ec2.md
The page includes links to startup an EC2 instance in many regions.
It also includes information on how to use the labs.
=> Add page describing how to use AWS push button

_layouts/homepage.html
Merge this after the AWS and GCP pages have been reviewed and merged.
Depends on: https://github.com/kubevirt/kubevirt.github.io/pull/48
Depends on: https://github.com/kubevirt/kubevirt.github.io/pull/100
=> Activate links to AWS and GCP push button pages on homepage

_posts/2018-09-11-KubeVirt-Memory-Overcommit, _posts/2018-09-11-KubeVirt-Memory-Overcommit.markdown
I also get confused on the existence of the non-markdown file that if it should be removed. 
Great work and post, thanks!
=> Fix minor typos and remove unexpected line breaks

_posts/2018-09-11-KubeVirt-Memory-Overcommit, _posts/2018-09-11-KubeVirt-Memory-Overcommit.markdown
=> Fix typos in grammar/spacing

pages/gcp.md
- Fix the header styling for the GCP page.
- Change duplicate "Step 2" to "Step 3".
fixes https://github.com/kubevirt/kubevirt.github.io/issues/117
fixes https://github.com/kubevirt/kubevirt.github.io/issues/118
=> Fix GCP Header Styling

_sass/_buttons.scss
Avoid to use font-awesome just to use 1 icon, if you decide to add more icons/fonts/etc.. we'll see.
Fixes #116
=> Fixing #116 not using font-awesome just for an icon

pages/community.html, pages/community/contributing.md, pages/ec2.md, pages/gcp.md, pages/get_kubevirt.md, pages/privacy.md
fixes https://github.com/kubevirt/kubevirt.github.io/issues/128
=> set external links to open in a new tab

pages/get_kubevirt.md
https://github.com/kubevirt/kubevirt.github.io/issues/98
=> Update policies for KubeVirt >= 0.8.0

_posts/2018-10-09-containerized-data-importer.markdown
Signed-off-by: tavni <tavni@redhat.com>
=> Containerized-data-importer Introduction

pages/ec2.md, pages/gcp.md
Users may encounter problems either deploying their instance or 
experimenting with the labs. We should let them know where to submit 
their feedback.
=> Add section on where to report push button issues

_posts/2018-10-10-CDI-DataVolumes.markdown
* Complete blog post.
* Set date for October 11th.
=> post(datavolumes): Add CDI DataVolumes post

labs/kubernetes/lab1.md
Missed a few items that still referred to connecting to vnc console.
=> vnc removal cleanup

_posts/2018-11-16-new-volume-types.markdown, labs/ocp/lab1.md, labs/ocp/lab2.md
This is a blog about the recently added volume types configMap, secret and serviceAccount.
Please have a look @scollier @fabiand
=> New blog about configMap, secret and serviceAccount

_includes/head.html, pages/cluster-api-provider-external.md, pages/node-recovery.md
For:
- node-recovery
- cluster-api-external-provider
=> Add go imports records

pages/ec2.md
Updated EC2 pages with new AMIs.
=> EC2 images for KubeVirt 0.10.0

_posts/2018-11-26-kubevirt-at-kubecon-na.markdown
Update contributor meetup info due to room change.
=> Update contributor meetup due to room change

_posts/2018-11-20-ignition-support.markdown
pending on ignition PR https://github.com/kubevirt/kubevirt/pull/1657/files
=> Blog on ignition data support

_includes/scriptlets/get_kubevirt/04_create_vm.sh
This change updates the URL to the vm.yaml file and the version string used in deploying kubevirt.
=> update urls for vm.yaml

pages/quickstart_minikube.md
Ref: https://github.com/kubevirt/kubevirt/issues/2056
=> Add caveat about older Minikube which lacks vhost-net device

_includes/scriptlets/lab1/05_verify_testvm_instance.sh, _includes/scriptlets/lab1/test_spec.yaml, _includes/scriptlets/lab2/test_spec.yaml
Add demo test spec for lab1 and lab2 pages.
=> Create test specs for lab1 and lab2 demos

_includes/scriptlets/quickstart_minikube/04_setenv_version.sh, _includes/scriptlets/quickstart_minikube/test_spec.yaml
Create a test spec to confirm the [quickstart_minikube](http://kubevirt.io/quickstart_minikube/) demo web page.
This change adds an automated test specification that, when used wth the demo test system will execute and validate the steps to confirm that they behave as expected.
=> Add quickstart test spec

_data/blogs_toc.yml, pages/blogs/2019/posts.md
Create category for posts in 2019
=> Separate posts in 2019

_data/site_nav_pages.yml
Do not hardcode server uri, use relative path
=> Do not hardcode server uri, use relative path

_posts/2019-06-04-Kubevirt-vagrant-provider.markdown
This blog entry descrives how to use kubevirt provider.
=> [WIP] Blog: vagrant kubevirt provider

_posts/2018-08-08-kubevirtci.markdown
=> fix: links on kubevirtci blog post

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> feat: add github templates

labs/ocp/lab2.md
=> Fix link to old scollier repo

_posts/2018-07-03-Unit-Test-Howto.markdown
There's a broken link in a blog post, caused by kubevirt/kubevirt@0acbdb417a0f7721fca9b73bd4be97391bd0ed54
This PR points to a specific branch - the last one that includes the file in the currently referenced location.
=> Fix broken link by pointing to a specific version

pages/gcp.md
provide better info on how to locate gcp cloud image
> Fixes #
=> provide better info on how to locate gcp cloud image

pages/blogs/2017/posts.md, pages/blogs/2018/posts.md, pages/blogs/2019/posts.md, pages/blogs/community.md, pages/blogs/news.md, pages/blogs/releases.md, pages/blogs/uncategorized.md, pages/blogs/updates.md
Makes titles linkables
> Fixes #
Closes #265 
=> Add links to titles

labs/ocp/lab2.md
Fix broken link
/kind bug
> Fixes #
=> Fix broken link to requirements

OWNERS
Add Edu to list of reviewers/owners
> Fixes #
=> Add Edu Minguez to community team

pages/quickstart_minikube.md
Update the install guide with the addition of installing `virtctl` via [`krew`](https://krew.dev/)
> Fixes #
=> Update the install guide with the addition of installing via `krew`

_data/blogs_toc.yml
Hides community blog section which is empty
Closes #261 
> Fixes #
=> Hide community as it has no articles

scripts/update_changelog.sh
This script will autogenerate markdown files for each kubevirt release as articles
> Fixes #
=> Generation of changelog entries based on git log

scripts/update_changelog.sh
Fix filename -> basename
> Fixes #
=> Autorelease

OWNERS
=> Adjust owners of project

_data/labs_toc.yml, pages/quickstart_minikube.md
Moves minikube to have same citizen status as AWS or GCP on labs page
> Fixes #
/kind enhancement
=> Show minikube on labs like GCP or AWS

_data/site_nav_pages.yml, pages/labs.md
=> Show labs in menu

_posts/2019-03-14-More-about-Kubevirt-metrics.markdown
=> Replace absolute link for macro post_url

_posts/2019-05-21-kubevirt-with-ansible-part-1.markdown
Some edits, to be merged after #283
=> Updates to ansible post part 1

_posts/2018-03-08-changelog-v0.3.0.markdown, _posts/2018-04-06-changelog-v0.4.0.markdown, _posts/2018-05-04-changelog-v0.5.0.markdown, _posts/2018-06-11-changelog-v0.6.0.markdown, _posts/2018-07-04-changelog-v0.7.0.markdown, _posts/2018-09-06-changelog-v0.8.0.markdown, _posts/2018-10-04-changelog-v0.9.0.markdown, _posts/2018-11-08-changelog-v0.10.0.markdown, _posts/2018-12-06-changelog-v0.11.0.markdown, _posts/2019-01-11-changelog-v0.12.0.markdown, _posts/2019-01-15-changelog-v0.13.0.markdown, _posts/2019-02-04-changelog-v0.14.0.markdown, _posts/2019-03-05-changelog-v0.15.0.markdown, _posts/2019-04-05-changelog-v0.16.0.markdown, _posts/2019-05-06-changelog-v0.17.0.markdown, _posts/2019-06-05-changelog-v0.18.0.markdown
Catchup with missing changelogs
> Fixes #
=> Add missing changelogs

GUIDELINES.md
=> Replace links as it was failing with GitHub Pages build

OWNERS
https://www.youtube.com/watch?v=EecgsR5ZaQM
> Fixes #
=> Add Pedro to owners

OWNERS
=> Move relocations to emeritus

TODO.md, _config.yml
=> Add TODO of pending ideas to define on the website

_posts/2019-07-12-website-roadmap.markdown
=> Add Post about TODO.md for call to action

TODO.md
=> Add FAQ in TODO

_includes/scriptlets/quickstart_minikube/04_setenv_version.sh
fixes #300 detected by jparrill
**Does this PR fix any issue?*
Fixes #300 
As we talked before, small fix to address a version removing the "$0-whatever"
=> fixing issues/300

_posts/2019-06-10-NodeDrain-KubeVirt.markdown, _posts/2019-07-30-NodeDrain-KubeVirt.markdown
Signed-off-by: shegde <shegde@redhat.com>
=> NMO-BlogPost

_posts/2019-08-01-Kubevirt-CR-Condition-Types-Rename.markdown
=> Alert on CR Condition Rename

_includes/head.html
=> Add replace node-recovery repo with machine-remediation-operator

pages/machine-remediation-operator.md, pages/node-recovery.md
=> Change node-recovery page to machine-remediation-operator

_posts/2019-07-05-changelog-v0.19.0.markdown
=> Add release 0.19.0 post

labs/manifests/pvc_fedora.yml
=> Use 'master' URL to use Fedora MirrorManager to redirect

_posts/2019-08-09-changelog-v0.20.0.markdown
=> New release

_posts/2019-07-08-kubevirt-with-ansible-part-2.markdown
CDI is a moving target. Update the ansible blog post to reflect current state.
=> ansible2: update cdi info

Jenkinsfile, tests/README.md, tests/ansible/aws-cleanup.yml, tests/ansible/aws-provision.yml, tests/ansible/gcp-cleanup.yml, tests/ansible/gcp-provision.yml, tests/ansible/lab1.yml, tests/ansible/lab2.yml, tests/ansible/minikube-cleanup.yml, tests/ansible/minikube-provision.yml, tests/expect/cirros-login.exp, tests/shell/cleanup.sh, tests/shell/disable-hostpath-minikube.sh, tests/shell/lab.sh, tests/shell/provision-and-destroy.sh
This work has done by Joel Davis from https://github.com/joeldavis84/kvio-lab-testing
Those tests will use the images created by joeldavis84/kvio-lab-images and then execute the tests over GCE and AWS ensuring that the latests images in conjunction with labs works fine. This is an intermedium step until the final result, which will be executed those tests on Prow CI/CD to be standard with all the repos over Kubevirt Org.
=> Added tests to Try It Button on Kubevirt.io.

.travis.yml
=> Remove gem install as it's done via bundle

.travis.yml, _includes/head.html
=> Add gtag like in metal3 site

_config.yml, _includes/head.html
=> Parameter for gtag

_posts/2019-04-17-Hyper-Converged-Operator.markdown
Fix broken links on HCO post
> Fixes #
=> Fix broken links

_config.yml, _includes/head.html, _includes/metas-ogp.html
=> Add OGP headers

labs/kubernetes/lab2.md
Related with #323 
Add NOTE about environment/lab assumptions/limitations
> Fixes #
=> Add warning for deploying on one node because of hostpath

_posts/2019-09-09-changelog-v0.21.0.markdown
=> Add release notes

_includes/metas-ogp.html
Only provide ogp type article for posts 
> Fixes #
=> Provide type article only on posts

_config.yml, _includes/metas-ogp.html
**What this PR does / why we need it**: addind missing ogp tags to be ogp compliance.
> Fixes #332
=> adding missing ogp tags type and image

_posts/2019-09-09-CNCF-Sandbox.md
=> Add publication on cncf sandbox

_config.yml
=> Use relative path

_includes/metas-ogp.html
=> Remove trailing

TODO.md, pages/privacy.md
=> Add netlify usage to privacy page

_config.yml
www domain is not resolving, force web to use 'kubevirt.io' instead
> Fixes #
=> Use domain without www

_posts/2018-04-25-KubeVirt-Network-Deep-Dive.markdown, _posts/2018-10-03-KubeVirt-Network-Rehash.markdown
Those two articles use different way to specify images than the other ones in the website. Making all of them work the same way can help detect issues like the DNS issue that raised initially this 'fix'
> Fixes #
=> Fix images in network deep dive

_config.yml, _includes/head.html
We should use Adobe DTM for analytics as standard
=> Remove GA code

Rakefile
=> Update Rakefile for domain without www

_posts/2019-10-09-KubeVirt_k8s_crio_from_scratch.md
Lowers heading levels by one and remove duplicate title (post title vs in-text title)
> Fixes #
=> Adjust heading levels

_includes/scriptlets/lab2/14_minikube_ssh_vm1.sh, _includes/scriptlets/lab2/15_minikube_virtctl_expose_ssh_nodeport.sh, _includes/scriptlets/lab2/16_minikube_vm_ip.sh, _includes/scriptlets/lab2/17_ssh_from_outer_minikube.sh, labs/kubernetes/lab2.md, labs/manifests/vm1_pvc.yml
Clarifies the process of running Fedora30 on minikube 
> Fixes #
It fixes #351 by clarifying the process of importing a Fedora cloud image in Minikube and being able to run all the steps, i.e accesing the VMI from outside Minikube.
=> Clarifies running lab2 on minikube - issue #351

_posts/2019-10-10-changelog-v0.22.0.markdown
=> Add v022 release notes

Rakefile
Feat: Added an option on Rakefile that allows to avoid url_swap passing a parameter
Fixes #345 
We need to change the periodic Jobs on project-infra
=> Feat: Rakefile param to avoid url_swap on demand

scripts/update_changelog.sh
=> fixing naming, KubeVirt instead of Kube Virt

_posts/2019-10-09-KubeVirt_k8s_crio_from_scratch.md, _posts/2019-10-16-KubeVirt_k8s_crio_from_scratch_installing_kubernetes.md
Adding second blogpost and changing first post to point to the second one
2nd blog post: https://deploy-preview-370--kubevirtio.netlify.com/2019/kubevirt_k8s_crio_from_scratch_installing_kubernetes
1st blog post: https://deploy-preview-370--kubevirtio.netlify.com/2019/kubevirt_k8s_crio_from_scratch
> Fixes #
=> Adding second blogpost and changing first post to point to the second one

tests/ansible/aws-provision.yml
=> Fix URL for using the CIB artifacts

_posts/2018-03-08-changelog-v0.3.0.markdown, _posts/2018-04-06-changelog-v0.4.0.markdown, _posts/2018-05-04-changelog-v0.5.0.markdown, _posts/2018-06-11-changelog-v0.6.0.markdown, _posts/2018-07-04-changelog-v0.7.0.markdown, _posts/2018-09-06-changelog-v0.8.0.markdown, _posts/2018-10-04-changelog-v0.9.0.markdown, _posts/2018-11-08-changelog-v0.10.0.markdown, _posts/2018-12-06-changelog-v0.11.0.markdown, _posts/2019-01-11-changelog-v0.12.0.markdown, _posts/2019-01-15-changelog-v0.13.0.markdown, _posts/2019-02-04-changelog-v0.14.0.markdown, _posts/2019-03-05-changelog-v0.15.0.markdown, _posts/2019-04-05-changelog-v0.16.0.markdown, _posts/2019-05-06-changelog-v0.17.0.markdown, _posts/2019-06-05-changelog-v0.18.0.markdown, _posts/2019-07-05-changelog-v0.19.0.markdown, _posts/2019-08-09-changelog-v0.20.0.markdown, _posts/2019-09-09-changelog-v0.21.0.markdown, _posts/2019-10-10-changelog-v0.22.0.markdown, scripts/update_changelog.sh
=> Change bot name

_posts/2019-10-23-KubeVirt_k8s_crio_from_scratch_installing_KubeVirt.md
**What this PR does / why we need it**: third post of the series of 3.
https://deploy-preview-379--kubevirtio.netlify.com/2019/kubevirt_k8s_crio_from_scratch_installing_kubevirt
=> Third blogpost of the series of 3

_posts/2019-10-09-KubeVirt_k8s_crio_from_scratch.md, _posts/2019-10-16-KubeVirt_k8s_crio_from_scratch_installing_kubernetes.md
**What this PR does / why we need it**: add links to the rest of the blogposts
> Fixes #
=> K8s third blogpost modifications (add links between blogposts)

_posts/2019-10-09-KubeVirt_k8s_crio_from_scratch.md
… provide the VM
Clarifies the hardware needed to follow the blog post. Also adds some information on how to provide the necessary resources (~vm)
> Fixes #
This information has been also PR'ed to Pedro as well in his personal repo
=> Adding resources needed to run the blog post and information about deploying

tests/README.md, tests/shell/lab.sh
=> Point to cloud-image-builder repo and adjust format

_posts/2019-10-16-KubeVirt_k8s_crio_from_scratch_installing_kubernetes.md
**What this PR does / why we need it**: adds a link at the end of the blogpost to get it easy for the user to get to the next chapter
> Fixes #
=> adding a link in the end of the post to the next blogpost in the series

_posts/2019-10-09-KubeVirt_k8s_crio_from_scratch.md, _posts/2019-10-16-KubeVirt_k8s_crio_from_scratch_installing_kubernetes.md, _posts/2019-10-23-KubeVirt_k8s_crio_from_scratch_installing_KubeVirt.md
**What this PR does / why we need it**: little modification based on pep's feedback
> Fixes #
=> Pep feedback changes

tests/shell/lab.sh, tests/shell/provision-and-destroy.sh
=> Change to tests folder before starting the test

tests/shell/lab.sh, tests/shell/provision-and-destroy.sh
=> Simplify CD

Jenkinsfile, tests/ansible/lab2.yml, tests/shell/lab.sh
=> Validationbatch1

_includes/head.html, pages/machine-remediation-operator.md, pages/machine-remediation.md
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
> Fixes #
=> Change the name of the machine-remediation-operator repository

tests/ansible/gcp-cleanup.yml, tests/ansible/gcp-provision.yml, tests/ansible/lab1.yml, tests/ansible/lab2.yml, tests/ansible/minikube-cleanup.yml
=> Adjust playbooks for Lab validation

_posts/2019-07-12-website-roadmap.markdown, _posts/2019-08-01-KubeVirt-CR-Condition-Types-Rename.markdown, _posts/2019-08-09-Kubevirt-CR-Condition-Types-Rename-Now-ACTIVE.markdown, _posts/2019-10-31-prow-jobs-for-kubevirt.markdown
Documents on Prow: <https://deploy-preview-371--kubevirtio.netlify.com/2019/prow-jobs-for-kubevirt.html>
> Fixes #
=> Prow documentation update

_posts/2019-11-04-changelog-v0.23.0.markdown
Add release note for 0.23
> Fixes #
=> Add 0.23 release notes

_posts/2018-03-08-changelog-v0.3.0.markdown, _posts/2018-04-06-changelog-v0.4.0.markdown, _posts/2018-05-04-changelog-v0.5.0.markdown, _posts/2018-06-11-changelog-v0.6.0.markdown, _posts/2018-07-04-changelog-v0.7.0.markdown, _posts/2018-09-06-changelog-v0.8.0.markdown, _posts/2018-10-04-changelog-v0.9.0.markdown, _posts/2018-11-08-changelog-v0.10.0.markdown, _posts/2018-12-06-changelog-v0.11.0.markdown, _posts/2019-01-11-changelog-v0.12.0.markdown, _posts/2019-01-15-changelog-v0.13.0.markdown, _posts/2019-02-04-changelog-v0.14.0.markdown, _posts/2019-03-05-changelog-v0.15.0.markdown, _posts/2019-04-05-changelog-v0.16.0.markdown, _posts/2019-05-06-changelog-v0.17.0.markdown, _posts/2019-06-05-changelog-v0.18.0.markdown, _posts/2019-07-05-changelog-v0.19.0.markdown, _posts/2019-08-09-changelog-v0.20.0.markdown, _posts/2019-09-09-changelog-v0.21.0.markdown, _posts/2019-10-10-changelog-v0.22.0.markdown, _posts/2019-11-04-changelog-v0.23.0.markdown, scripts/update_changelog.sh
Update code in script for log generation and run against current articles
> Fixes #
Closes #391 
=> Fix replacement for date

Jenkinsfile, tests/ansible/gcp-provision.yml, tests/ansible/lab2.yml
Lab improvements on scripts, notifications, etc
> Fixes #
=> Labimprovements

Jenkinsfile
Change subject of slack notifications
> Fixes #
=> Change subject of slack notifications

Jenkinsfile
Throw exception directly on Jenkins Failure
> Fixes #
=> Throw exception directly on Jenkins Failure

Jenkinsfile
Save artifacts in Jenkinsfile
> Fixes #
=> Save artifacts in Jenkinsfile

_posts/2019-04-17-Hyper-Converged-Operator.markdown
=> Remove duplicated '/'

_posts/2019-11-12-kubecon-na-2019.md
This adds a blog post to summarize KubeVirt's presence at the upcoming KubeCon in San Diego.
> Fixes #
=> [blog] Add blog post about KubeVirt at KubeCon

_posts/2019-11-12-kubecon-na-2019.md
This turns the address to register for the KubeCon meetup into an actual link so people can click away.
> Fixes #
=> KubeCon blog post: fix link

_posts/2019-11-12-kubecon-na-2019.md
=> Typo fixed in the blogpost about KubeCon and KubeVirt

_posts/2019-11-11-Access-Virtual-Machines-graphic-console-using-noVNC.markdown
Reverts kubevirt/kubevirt.github.io#410
Reverting as per Pep's comments
=> Revert "Fix typo"

Jenkinsfile
Reenable minikube testing on GCP
=> Reenable minikube testing

_posts/2019-11-28-KubeVirt_basic_operations_video.md, pages/videos/tech-demos.md
**What this PR does / why we need it**: kubevirt basic operations video blogpost
=> Adding Kubevirt basicops video blogpost

_posts/2019-12-04-KubeVirt_lab1_use_kubevirt.md, labs/kubernetes/lab1.md
> Fixes #
**Special notes for your reviewer**: to publish in December 4th.
=> Adding KubeVirt lab 1 post with video embed (December 4th)

_posts/2019-12-03-changelog-v0.24.0.markdown
=> Article on 0.24

_posts/2019-12-10-KubeVirt_lab2_experiment_with_cdi.md, labs/kubernetes/lab2.md
**What this PR does / why we need it**: new blogpost about the youtube video kubevirt lab2
**Special notes for your reviewer**: to be published on December 10th
=> adding kubevirt lab2 video blogpost

Jenkinsfile, _data/labs_toc.yml, labs/kubernetes/lab2.md, labs/kubernetes/lab3.md, tests/README.md, tests/ansible/lab3.yml, tests/shell/uninstall-kubevirt.sh
Add LAB for KubeVirt Upgrades
https://deploy-preview-419--kubevirtio.netlify.com/labs/kubernetes/lab3.html
=> LAB3 - KubeVirt Upgrades

tests/ansible/lab3.yml
Fixes command for Lab3 execution
> Fixes #
=> Fix command for ansible lab3

tests/ansible/lab3.yml
=> Add some delays and retries

tests/ansible/lab3.yml
Add sleep to allow operator to create containers
> Fixes #
=> Add sleep to allow operator to create containers

tests/ansible/lab3.yml
Use the apply approach for upgrade
> Fixes #
=> Apply Operator to perform upgrade

_posts/2019-07-29-How-To-Import-VM-into-Kubevirt.markdown
=> Fix virtctl image-upload command

_posts/2020-01-13-changelog-v0.25.0.markdown
=> Release 0.25

_includes/head.html, _layouts/default.html
Update to latest code for DTM -> DPAL transition for analytics
> Fixes #
=> Update DTM -> DPAL code for analytics

_posts/2018-03-08-changelog-v0.3.0.markdown, _posts/2018-04-06-changelog-v0.4.0.markdown, _posts/2018-06-11-changelog-v0.6.0.markdown, _posts/2018-07-04-changelog-v0.7.0.markdown, _posts/2018-09-06-changelog-v0.8.0.markdown, _posts/2018-10-04-changelog-v0.9.0.markdown, _posts/2018-11-08-changelog-v0.10.0.markdown, _posts/2018-12-06-changelog-v0.11.0.markdown, _posts/2019-01-11-changelog-v0.12.0.markdown, _posts/2019-01-15-changelog-v0.13.0.markdown, _posts/2019-02-04-changelog-v0.14.0.markdown, _posts/2019-03-05-changelog-v0.15.0.markdown, _posts/2019-04-05-changelog-v0.16.0.markdown, _posts/2019-06-05-changelog-v0.18.0.markdown, _posts/2019-07-05-changelog-v0.19.0.markdown, _posts/2019-08-09-changelog-v0.20.0.markdown, _posts/2019-09-09-changelog-v0.21.0.markdown, _posts/2019-10-10-changelog-v0.22.0.markdown, _posts/2019-11-04-changelog-v0.23.0.markdown, _posts/2019-12-03-changelog-v0.24.0.markdown, _posts/2020-01-13-changelog-v0.25.0.markdown, scripts/update_changelog.sh
Update release notes to use long name for month for solve sorting issues
=> Use month long name

_posts/2020-01-21-KubeVirt_lab3_upgrade.md, labs/kubernetes/lab2.md, labs/kubernetes/lab3.md
**What this PR does / why we need it**: adds a blogpost about the lab3 video
**Special notes for your reviewer**: to be published in January 21st 
Preview at: https://deploy-preview-432--kubevirtio.netlify.com/2020/kubevirt_lab3_upgrade
=> Kubevirt lab3 video blogpost

_includes/metas-ogp.html
=> Add spacing in headers

_posts/2019-04-17-Hyper-Converged-Operator.markdown, _posts/2019-05-21-kubevirt-with-ansible-part-1.markdown, _posts/2019-07-29-How-To-Import-VM-into-Kubevirt.markdown, _posts/2019-07-30-NodeDrain-KubeVirt.markdown, _posts/2019-12-04-KubeVirt_lab1_use_kubevirt.md, _posts/2019-12-10-KubeVirt_lab2_experiment_with_cdi.md, _posts/2019-12-17-KubeVirt_UI_options.md, _posts/2020-01-21-KubeVirt_lab3_upgrade.md, labs/kubernetes/lab2.md
Use local links instead of external ones
> Fixes #
=> Uselocallinks

.travis.yml
Forces travis to push against master branch to GH pages serving
> Fixes #
=> Push to master on source updates

.travis.yml
> Fixes #
Define folder to use for GH publishing
=> Define folder to use for GH publishing

_posts/2019-07-12-website-roadmap.markdown
Fixes link to TODO file.
> Fixes #
=> Fix branch link

_config.yml
Disable future posts until date arrives
> Fixes #
Closes #409
=> Disable future posts until date arrives

404.html
Shows custom kubevirt message on page not found
> Fixes #
=> Add 404 custom page for GH

404.html
Try to fix 404 behavior
> Fixes #
=> Try to fix 404 behavior

docs.html, search.json
Document search was hidden in the website, this reenables/fixes the code
> Fixes #
=> Fix doc search

_includes/header.html, _layouts/search.html, search.html
Reenables search functionality in the website
> Fixes #
Closes #449 
Preview at: https://deploy-preview-452--kubevirtio.netlify.com/
=> Reenable search functionality in website

_data/blogs_toc.yml, pages/blogs/2020/posts.md
Show 2020 posts that are still hidden on website
> Fixes #
=> Show 2020 posts

.travis.yml
Fixes GH trying to reprocess website
> Fixes #
=> Tell GH to ignore Jekyll

.travis.yml, _data/amis.json, pages/ec2.md
Fill-in AMI details for EC2 page in the meantime
Closes #365
=> Dinamically generate amis

_includes/head.html, _layouts/post.html
Prepare 'base' for DevConfCZ article
> Fixes #
=> Backend for galleria

_layouts/search.html
Use relative links in search template
> Fixes #
=> Use relative links in search template

_posts/2019-11-28-KubeVirt_basic_operations_video.md
Fix date to match filename
> Fixes #
=> Fix date to match filename

_posts/2020-01-21-KubeVirt_lab3_upgrade.md
Fix year to match filename
> Fixes #
=> Match year in filename

_includes/header.html, _sass/_autocomplete.scss, css/main.scss
Autosuggest keywords
> Fixes #
Preview at: https://deploy-preview-463--kubevirtio.netlify.com/
=> Autocomplete suggestions

_includes/header.html
Block submit form if empty
> Fixes #
Closes #464 
https://deploy-preview-465--kubevirtio.netlify.com/
=> Do not submit search form if empty

_layouts/search.html
Excludes some contents from index
> Fixes #
Closes #466 
=> Filter search index contents

_layouts/search.html
Current filtering does leave some /build that are generated in the other index loops
> Fixes #
Related #467 #466 
=> Do more filtering

_layouts/search.html
Exclude files without plugin from indexing
> Fixes #
=> Exclude files without plugin from indexing

_includes/footer.html, _sass/_footer.scss
Show slack link at footer
> Fixes #
Re: https://groups.google.com/forum/#!topic/kubevirt-dev/x5yHV6T5Jdg
=> Showcase slack link

GUIDELINES.md
Updates contributing to add reference to admonitions
> Fixes #
=> Update guidelines to show admonitions

_layouts/search.html
Fixes index generation by using pages
> Fixes #
Closes #481 
=> Fix loop generation

_layouts/search.html
Compare against 'nil' instead of ""
> Fixes #
Closes #485 
=> Exclude documents with no title

_layouts/search.html
Improve search by also indexing authors of blog posts
> Fixes #
/kind enhancement
=> Index authors on search

_posts/2018-10-09-containerized-data-importer.markdown
Fixes broken link on CDI article
> Fixes #
=> Fix link to rbac

README.md
Instruct users to use --future when checking for future-dated posts
> Fixes #
=> Use --future for rendering future-dated posts

pages/community.html
Adds link to get invite
> Fixes #
Closes #484 
Preview at https://deploy-preview-499--kubevirtio.netlify.com/community/
=> Add link to get an invite to K8S slack instance

_posts/2017-07-18-technology-comparison.md
This moves a markdown article by Fabian to 'post' format so that it appears in the website
> Fixes #
Preview at: https://deploy-preview-501--kubevirtio.netlify.com/2017/technology-comparison.html
=> Move old markdown to article

_posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
**What this PR does / why we need it**: workaround the bugfix found with the code inside a bullet after some html code.
> Fixes #
**Special notes for your reviewer**: merge if it works
Preview at https://deploy-preview-506--kubevirtio.netlify.com/2020/kubevirt-installing_microsoft_windows_from_an_iso
=> code inside a bullet bugfix try1

labs/kubernetes/lab1.md, labs/kubernetes/lab2.md, labs/kubernetes/lab3.md
Add links to katacoda scenarios on each lab
> Fixes #
Check each lab page for the upper link
=> Add Katacoda scenario links

_posts/2018-09-12-attaching-to-multiple-networks.markdown, _posts/2018-10-03-KubeVirt-Network-Rehash.markdown, _posts/2020-01-24-OKD-web-console-install.md
Change to use post_url macro instead of url constructed of site + hardcoded url
=> Use post_url macro

_posts/2018-04-25-KubeVirt-Network-Deep-Dive.markdown
Add pointer from older article to newer one
> Fixes #
=> Pingback to updated article

_galleries/2020-02-03-Fosdem2020-communty-presence.md, assets/galleria/fosdem2020.json
Fosdem 2020 pictures in twitter
> Fixes #
Preview at: https://deploy-preview-471--kubevirtio.netlify.com/2020/fosdem2020-communty-presence
=> Fosdem 2020 pictures from twitter

_config.yml, _data/site_nav_pages.yml, _layouts/search.html, pages/gallery.md
Spinoff gallery section
> Fixes #
preview at: https://deploy-preview-474--kubevirtio.netlify.com/gallery/
=> Add gallery category under blogs

_includes/header.html
Fill keywords suggestion from article tags
> Fixes #
=> Use article tags for populating keywords suggestions

_includes/metas-ogp.html
Set tags to article tags
> Fixes #
=> Set default tags to article tags

_includes/footer.html, pages/privacy.md
Put netlify link on mainpage
> Fixes #
Preview at: https://deploy-preview-516--kubevirtio.netlify.com/
=> Put netlify banner on mainpage as per requirements for their service

_sass/_syntax.scss, js/copy.js
Scroll code blocks instead of page
> Fixes #
=> Scrollcode

GUIDELINES.md
Document on how to use image display for big images
> Fixes #
=> Document how to use gallery

_config.yml, js/copy.js
=> Disable line numbers

_includes/footer.html, _sass/_footer.scss
Give visibility to youtube channel which has been filled with lot of material recently
> Fixes #
=> Show youtube link to KubeVirt channel

_includes/head.html
Review sitemap status on crawlers
=> Add site verification

_includes/head.html
=> Amend code

_posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
Adds internal anchor to the installation section from the admonition 
> Fixes #
=> Add internal anchor to installation section

_layouts/search.html
**What this PR does / why we need it**: fixes a possible xss attack through the search results
> Fixes #
=> fixing possible xss attack through the search results

_posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md, package-lock.json
What this PR does / why we need it:
This PR fixes the issue found in some code blocks in the blogpost "KubeVirt: installing Microsoft Windows from an ISO", the code blocks are not rendered properly and they are being shown as markdown code instead of html code.
Special notes for your reviewer: check if the code blocks after the sentence "To upload data to the cluster, the cdi-uploadproxy service must be accessible from outside the cluster. In a production environment, this probably involves setting up an Ingress or a LoadBalancer Service." are rendered properly or you still can see the ```sh annotations.
=> amend to the PR windows_blogpost_issue

_posts/2020-04-28-KubeVirt-Architecture-Fundamentals.md
In this blog post I outline the core set of design decisions that shaped KubeVirt into what it is today. I'm essentially telling the story of how why KubeVirt is the way it is.
=> blog post: KubeVirt Architecture Fundamentals 

_posts/2020-04-30-KubeVirt-Operation-Fundamentals.md
This blog post outlines our approach to operating KubeVirt, including installs and updates.
=> blog post: outlining KubeVirt operation fundamentals

_posts/2019-01-22-An-overview-to-KubeVirt-metrics.markdown, _posts/2019-03-14-More-about-Kubevirt-metrics.markdown, _posts/2019-07-29-How-To-Import-VM-into-Kubevirt.markdown, _posts/2019-07-30-NodeDrain-KubeVirt.markdown, _posts/2019-10-23-KubeVirt_k8s_crio_from_scratch_installing_KubeVirt.md, _posts/2019-10-30-KubeVirt_storage_rook_ceph.md, _posts/2019-11-28-KubeVirt_basic_operations_video.md, _posts/2019-12-04-KubeVirt_lab1_use_kubevirt.md, _posts/2019-12-10-KubeVirt_lab2_experiment_with_cdi.md, _posts/2020-01-21-KubeVirt_lab3_upgrade.md, _posts/2020-01-24-OKD-web-console-install.md, _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md, _posts/2020-02-25-Advanced-scheduling-with-affinity-rules.md
**What this PR does / why we need it**: fixes broken links to the user-guide documentation webpage from multiple blogposts
fixes #557
> Fixes #
=> fixing broken links to the user-guide webpage in multiple blogposts

.yaspeller.json, _posts/2020-03-22-Live-migration.md
Adds information about Live Migration in KubeVirt
> Fixes #
Preview at: https://deploy-preview-552--kubevirtio.netlify.com/2020/live-migration
=> Document on Live Migration in KubeVirt

_posts/2019-11-11-Access-Virtual-Machines-graphic-console-using-noVNC.markdown
This fixes a link in a blog post that broke today.
> Fixes #
This is preventing other PRs to merge
=> Fix broken link to kubectl proxy doc

.gitignore, _posts/2018-04-25-KubeVirt-Network-Deep-Dive.markdown, _posts/2018-05-08-KubeVirt-objects.markdown, _posts/2018-05-16-KubeVirt-API-Access-Control.markdown, manifest.json
Some old blog posts had links that stopped working. Correct them.
Fixes #575
I corrected the user-guide links in the blog post affected by #575 but in the process I found that more need fixing (and hopefully we can find how to make sure these are properly checked). Created #576 to track that further.
For now, this PR should help keep the CI happy.
=> Fix a few broken links in blog posts

_posts/2020-06-22-win_workload_in_k8s.md
/bug
A bad title got by myself and peer reviewers.  I updated so that it makes sense.
**Does this PR fix any issue?**
=> Create blog post for KubeVirt + footnote title fix

_includes/labs-description.md
=> Fix labs-description: Remove localhost:24000 from hrefs

_posts/2019-10-30-KubeVirt_storage_rook_ceph.md
Fixes link in old post that is now broke
=> Link fix to satisy CI

README.md
Update README to add cmd for link checker
=> Update README to add cmd for link checker

README.md
/enhancement
Update README to add cmd for link checker
=>  Update README to add cmd for link checker (2nd try)

.yaspeller.json, _includes/head.html, pages/ssp-operator.md
Signed-off-by: Omer Yahud <oyahud@redhat.com>
=> Added go-import for ssp-operator

_posts/2018-10-09-containerized-data-importer.markdown, _posts/2019-07-08-kubevirt-with-ansible-part-2.markdown, _posts/2019-10-31-jenkins-jobs-for-kubevirt-lab-validation.markdown, pages/quickstart_kind.md
Fix broken links in historical pages found by new Rakefile and htmlproofer options
=> Fix broken links in historical pages

TODO.md
Remove two items from the TODO list for the website:
- The blog post higlights on the front page was implemented in #612
- Recent discussions led to discourage adding a FAQ in the website (see #298)
Fixes #298 
=> Update TODO list

_posts/2019-11-22-jenkins-ci-server-upgrade-and-jobs-for-kubevirt.markdown
=> Fix broken link

_includes/scriptlets/lab2/17_ssh_from_outer_minikube.sh
Signed-off-by: Spencer Krum <nibz@spencerkrum.com>
Updates the `ssh` command listed in Lab 2
Possibly the issue in https://github.com/kubevirt/kubevirt/issues/3934
> Fixes #
=> Update ssh command in Lab2

_posts/2020-10-21-Multiple-Network-Attachments-with-bridge-CNI.markdown
The links referenced in NNCP section are wrong; this commit updates
them.
=> Fix kubernetes-nmstate links

_layouts/labs.html
=> updates labs page

_posts/2020-10-21-Multiple-Network-Attachments-with-bridge-CNI.markdown
Signed-off-by: Arnon Gilboa <agilboa@redhat.com>
Fixes minor bugs in the "Multiple Network Attachments with bridge CNI" post.
=> Fix NAD example

pages/quickstart_kind.md
This fixes a small typo that mentions a minikube instance inside of the KinD docs
> Fixes #
=> Fix minikube -> kind typo

_layouts/default.html, _layouts/post.html
=> remove disqus code

_includes/head.html, pages/cpu-nfd-plugin.md
Add import path for https://github.com/kubevirt/cpu-nfd-plugin
=> Add import path for https://github.com/kubevirt/cpu-nfd-plugin

_posts/2021-01-12-KubeVirt-Summit-announce.md, pages/summit.md
Add a landing page for the upcoming KubeVirt Summit
> Fixes #
=> Add a landing page for the KubeVirt Summit

_posts/2020-03-22-Live-migration.md
Signed-off-by: shubhindia <shubhindia123@gmail.com>
The labels need to be indented to work.
=> fir labels in Live Migration template

_posts/2020-02-25-Advanced-scheduling-with-affinity-rules.md, pages/summit.md
The CNCF kindly offered to host the upcoming KubeVirt event.
Red Hat had previously offered to cover the costs of the hosting platform, but this is no longer needed.
This updates the event landing page to reflect this.
> Fixes #
=> Update summit sponsorship

pages/summit.md
Updated information about the summit.
> Fixes #
=> Update summit times and registration details

pages/summit.md
We had to change the event for day 2
> Fixes #
=> Update event link

pages/summit.md
The KubeVirt Summit ended, so this PR updates the landing page to reflect that.
> Fixes #
=> Update summit page to reflect it finished

labs/manifests/vm.yaml
The image no longer exists on docker hub as we are now using quay.io
> Fixes #
=> update containerDisk image to use quay.io

_posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
Fixes #698 
Simple broken link fix
=> Corrected link text

pages/hostpath-provisioner-operator.md
Attempting to resolve 404 on /hostpath-provisioner-operator by turning it off and back on again.
=> Removing for website issue

pages/hostpath-provisioner-operator.md
=> Re-added hp operator page during debug of 404.

labs/kubernetes/lab1.md
Signed-off-by: ansijain <ansi.jain@india.nec.com>
> Fixes #
**Special notes for your reviewer**: NONE
=> Fixed VM name myvm->testvm

Makefile, README.md, _posts/2018-05-04-Deploying-KubeVirt-on-a-Single-oVirt-VM.markdown
Signed-off-by: Eran Ifrach <eifrach@redhat.com+>
**What this PR does**:
*  refactoring the README.md file.
* fix `make run` on Makefile
fixes #713
=> refactor README.md

pages/community.html
Signed-off-by: John Herr <joherr@redhat.com>
This adds a link on the community page to get a slack channel invite.
Fixes #700
=> Added slack invite to community page

_posts/2021-04-21-Automated-Windows-Installation-With-Tekton-Pipelines.md
I noticed one highlight wasn't working properly in the last blog.
~It should probably fix it, but let's wait for netlify to verify it.~
Works correctly.
@mazzystr
=> fix highlighting in a Automated Windows Installation blog post

_config.yml, pages/community.html
- fixes https://github.com/kubevirt/community/issues/104
=> Migrate KubeVirt shared cal to the CNCF account

README.md
=> Fixed merge artifacts

labs/manifests/vm.yaml, labs/manifests/vm1_pvc.yml
Update version of VMs in labs to v1
Issue raised on kubevirt-dev mailing list, thanks to 
Dinesh Reddy <reddydinesh258@gmail.com> for discovering and bringing to our attention.
=> Update to v1

pages/quickstart_cloud.md, pages/quickstart_kind.md, pages/quickstart_minikube.md
Signed-off-by: ansijain <ansi.jain@india.nec.com>
> Fixes #
=> Fixed Quickstart Labs Version Command

OWNERS
=> Update to OWNERS file

Makefile
FIXES #742 
Run `make check_spelling`
1) Initial test should fail with many spell checks.  `echo $?` should return 2 which will be the same as the Makefile error
2) Update Line159 and invalidate url.  `echo $?` should return 2 which will be the same as the Makefile error
3) Update Line159 and invalidate filename.  `echo $?` should return 2 which will be the same as the Makefile error
4) Update local yaspeller,json file with errors from above (this is gonna be painful ...) and then `rm -rf ./README.md`.  `make check_spelling` should complete successfully.  `echo $?` should return 0.
=> Fix check_spelling exit codes plus a couple cosmetics

Makefile
Fix check_spelling exit codes, speed plus cosmetics
**Does this PR fix any issue?**:
Fixes #730 
Fixes #744 
* Run `make check_links`
* Run `echo $?`
* Return should be 0
* Run `sed -i s/node_assignment/sdfsdf/g _posts/*Advanced-scheduling-with-affinity-rules*`
* Run `make check_links`
* Output should be ...
```
- ./_site/2020/Advanced-scheduling-with-affinity-rules.html
*  External link https://kubevirt.io/user-guide/operations/sdfsdf/#affinity-and-anti-affinity failed: 404 No error
HTML-Proofer found 1 failure!
``` 
* Run `echo $?`
* Output should be 1
* Run `git checkout _posts/*Advanced-scheduling-with-affinity-rules*`
* Run `sed -i s/affinity-and-anti-affinity/sdfsdf/g …
=> Fix check_spelling exit codes, speed plus cosmetics

Makefile, _posts/2021-04-30-intel-vgpu-kubevirt.md
=> Fix bad merge artifacts

OWNERS
Add @dhiller to approvers
> Fixes #
/cc @mazzystr
=> Add dhiller to approvers

Makefile, _galleries/2020-02-03-Fosdem2020-communty-presence.md, _posts/2019-10-31-prow-jobs-for-kubevirt.markdown, scripts/update_changelog.sh
Create build target for CI
This should be equal to the travis-ci script
=> Create build target for CI

OWNERS
=> Adding self to approvers/reviewers

pages/privacy.md
Signed-off-by: Josh Berkus <josh@agliodbs.com>
Switches the privacy policy to the correct one (Linux Foundation) and adds a link to email the maintainers.
=> Update privacy policy and mailing address for correct CNCF links.

OWNERS
Signed-off-by: Petr Horáček <phoracek@redhat.com>
I'd like to request an approve rights to help with reviewes and
maintenance.
Referrals:
- @fabiand
=> Add phoracek to owners

_layouts/default.html
=> Repair default template

_includes/scriptlets/lab2/08_get_vm_manifest.sh
=> Changed link to shorten and remove branch name

_posts/2019-07-30-NodeDrain-KubeVirt.markdown, _posts/2019-10-23-KubeVirt_k8s_crio_from_scratch_installing_KubeVirt.md
Similar to https://github.com/kubevirt/kubevirt.github.io/pull/788
Signed-off-by: ansijain <ansi.jain@india.nec.com>
> Fixes #
=> Changed link to shorten and remove branch name in posts

_posts/2019-10-31-prow-jobs-for-kubevirt.markdown, _posts/2021-08-13-Virtual-machines-in-Istio-service-mesh.md
Signed-off-by: Tyler Auerbeck <tauerbec@redhat.com>
This fixes some issues found by the markdown linter in the istio blog post.
N/A
=> Fix istio post linting

Makefile
=> Fix for lint CI issues

_posts/2019-07-29-How-To-Import-VM-into-Kubevirt.markdown
Remove duplicate paragraph that is already mentioned a few lines above.
=> Remove duplicate text

pages/videos/community/meetings.md
Signed-off-by: ansijain <ansi.jain@india.nec.com>
**What this PR does / why we need it**: To Add SIG - Performance & Scale Playlist to community meetings section.
> Fixes https://github.com/kubevirt/kubevirt.github.io/issues/801
=> Added SIG - Performance & Scale Playlist to community meetings section

_data/adopters.py
Update adopter.py, allow for other filetypes, add some checking
=> Update adopter.py, allow for other filetypes, add some checking

_posts/weekly/2017-10-28-This-Week-in-Kube-Virt-8.markdown
Fix for broken link found by link checker
=> Broken link fix

_includes/quickstarts/kubectl.md
This fixes the dead link to the kubernetes skew page.
Fixes #820
=> "Fixed link to k8s skew page, issue 820"

.pre-commit-config.yaml, README.md, _config/src/package.json
=> Last cleanup of offensive language.

pages/summit.md
Hey, our presenters from Korea had a TZ math error, and needed to have their slot moved. 
Please approve, @cwilkers
=> Change to Wednesday Summit schedule per presenter requirements.

_posts/2022-01-25-Dedicated-migration-network.md
This PR adds a blog post about dedicated migration networks.
=> blog: add post about dedicated migration networks

pages/summit.md
One of the talks has an incorrect title.
=> Minor fix for title of one talk, per speaker

index.html
Signed-off-by: katyamarova <marova.ekaterina@gmail.com>
Bugfix. Links to adopters on index page has missing href attributes.
**Does this PR fix any issue?**:
Fixes  #842
=> Fix for broken links to adopters on index page

Makefile
Fixes a couple targets in Makefile when running new container image (upcoming PR in project-infra)
fixes #850 
Local container build is still broken, will update project-infra with fixed Dockerfile
=> Fix check_links_selectors and run targets

_posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md, _posts/2022-05-09-KubeVirt-installing_Microsoft_Windows_11_from_an_iso.md, _posts/2022-08-02-KubeVirt-installing_Microsoft_Windows_11_from_an_iso.md
This is a first attempt at documenting Windows 11 installation.
There's a probably a lot to improve, in both the format and the content, so please don't hold back in your review!
=> Windows 11 installation blog post

_posts/2022-08-12-KubeVirt-Introduction-of-instancetypes.md
Adds a simple introductory blog post for instancetypes.
> Fixes #
=> blog: Add instancetype post

Makefile
This conflicts with gems like html-proofer that use it to pull in dev
dependencies [1][2].
[1] https://github.com/gjtorikian/html-proofer/commit/58c882ef1401aec2968c32efb85b299ae5d8b08e
[2] https://github.com/gjtorikian/html-proofer/commit/2873f06e1ddd02b09274ad8825becc6540a688c1
Fixes #862
=> Remove use of DEBUG env var from Makefile

_posts/2020-12-10-Customizing-images-for-containerized-vms.md, _posts/2021-10-13-Running-Realtime-Workloads.md, _posts/2022-06-28-KubeVirt-at-KubeCon-EU-2022.md, pages/summit.md
With the check_lint working, I was able to find a few pages that have sneaked in with non-ideal formatting.
**Does this PR fix any issue?** 
No issue, just opportunity when correcting the Dockerfile in https://github.com/kubevirt/project-infra/pull/2189
I left one piece of lint I don't fully agree is a problem. It might be nice to disable that rule properly at some point.
=> Corrected markdown lint

labs/kubernetes/lab3.md, pages/quickstart_cloud.md, pages/quickstart_kind.md, pages/quickstart_minikube.md
Old instructions target deprecated ConfigMap
New instructions target KubeVirt CR
Fixes #844
=> Updated instructions for enabling emulation

.github/ISSUE_TEMPLATE.md
Add a note to the issue filing template to redirect users with technical issues to kubevirt/kubevirt
> Fixes https://github.com/kubevirt/kubevirt.github.io/issues/870
=> Add a note directing users to KubeVirt's main repo for technical issues.

_includes/scriptlets/lab2/06_create_fedora_cloud_instance.sh
Signed-off-by: Mendy Man <conact@mendy.dev>
The existing one is 404
=> Update to latest Fedora Cloud base image

pages/quickstart_minikube.md
=> Add warning about broken minikube lab

_includes/quickstarts/virtctl.md
**What this PR does / why we need it**: Fixes Codeblock
=> update codeblock for virtctl

labs/kubernetes/lab3.md
> Fixes #874
Updated version form 0.20.1 to 0.56.1.
Please review and give feedback.
=> Version update

_posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
This type of networks allows connectivity to the physical network underlay.
This PR shows how to create OVN-K secondary networks to interconnect VMs
on an SDN network with access to the physical network underlay.
> Fixes #
=> blog: post about secondary ovn-k localnet networks

_includes/head.html, pages/managed-tenant-quota.md
=> Added go-import for mtq-operator 

_posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
Fix small incorrect details on the first example.
Add docker underlay bridge name detection command.
> Fixes #
=> localnet: various small fixes

_posts/2023-09-06-KubeVirt-on-autoscaling-nodes.md
This cross-posts a blog post on using KubeVirt with Cluster Autoscaler. The original can be found at: https://relaxdiego.com/2023/08/kubevirt-cas-baremetal.html
=> Add blog on KubeVirt and Cluster Autoscaler

_includes/head.html, pages/applications-aware-quota.md
=> Added go-import for aaq-operator

OWNERS
Adds @aburdenthehand as approver, since he's the community facilitator.
Puts @mazzystr to emeritus approvers and removes him from reviewers, since he's gone to NASA :smiling_face_with_tear: 
> Fixes #
/cc @fabiand @stu-gott
=> Add aburden as approver, put mazzystr to emeritus

_includes/head.html, pages/application-aware-quota.md
Because of the repo renaming
> Fixes #
=> Add another url for aaq operator

_includes/head.html
=> Add aaq api repo for imports

labs/kubernetes/lab1.md
Review the lab1 tutorial, verify it is still working and add some details about vm / vmi difference
> Fixes #938
**Special notes for your reviewer**: 
THis is part fo the Kubecon 2024 Paris Contribfest
=> Review and update of lab1

_includes/scriptlets/lab2/06_create_fedora_cloud_instance.sh
=> Updating Cloud base image to download
