kubevirt/kubevirt.github.io

- contrib.md
Remove reference to Trello for task tracking, since it was decided that this
would not be a formal part of the project workflow.
Add link to the new "project-infra" git repository.
> Update contributor content

- pages/privacy.md
Per discussion.
One prerequisite: we need to have an email alias privacy@kubevirt.io that forwards to project leaders, or whomeever is going to deal with privacy requests.
> Add GDPR-compliant privacy policy.

- _includes/head.html
- pages/kubevirt.md
Hi,
It would be great if we could finally resolve https://github.com/kubevirt/kubevirt/issues/610.
Here is a very primitive solution to make 
```
go get -d kubevirt.io/kubevirt
```
work.
In order to make it work, it would be required that we can also hit the page with `https://kubevirt.io/kubevirt` and not just via `https://www.kubevirt.io/kubevirt`.
I am open for better suggestions.
> Allow the usage of "go get -d kubevirt.io/kubevirt"

- pages/get_kubevirt.md
Change the get start with kubevirt page.
rename ovms to vms and vms to vmis
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubevirt/kubevirt.github.io/56)
> Rename ovm and vm

- _includes/head.html
- pages/containerized-data-importer.md
Enables `go get kubevirt.io/containerized-data-importer` by adding the respective meta tag and page.
> Adds go get kubevirt.io/containerized-data-importer support

- pages/labs/kubernetes/lab6/lab6.md
- pages/labs/kubernetes/lab7/lab7.md
- pages/labs/manifests/pvc_fedora.yml
- pages/labs/manifests/storage-setup.yml
- pages/labs/manifests/vm1_pvc.yml
Substituted oc commands for kubectl.
Trimmed out content that referenced content from previous labs.
* ara app references
* references to golden-images which didn't seem to be required
Included hostpath storage class setup in lab7.
Add manifests directory to hold some files that were previously in
the administrator directory in https://github.com/scollier/kubevirt-tutorial/tree/master/administrator.
> Creates versions of lab6 and lab7 for Kubernetes

- pages/docs/installation.md
The documentation on this page incorrectly uses the value "allowEmulation" for the configmap.  The correct value is "useEmulation".
> Incorrect value for configmap

- README.md
The command was missing the "jekyll" executable and ended up trying
to execute "serve".
> Fix jekyll container start command

- _sass/_tables.scss
- css/main.scss
This PR updates the styling of the default markdown tables when rendered in HTML. The styling mimics the Bootstrap 4 `.table-bordered` styling that is usually applied with specifying the class.
**Example:**
> fix(tables): update table styling for markdown tables

- pages/ec2.md
Should not default to us-east-1 for other regions.
> Fix region parameter in AWS links

- pages/ec2.md
Change the AMIs from v0.8.0-alpha.1 to v0.8.0.
Also removed right column alignment now that Adam added the new
table styling.
> Update AWS AMIs to v0.8.0 and fix column alignment

- Rakefile
This PR activates the tests for broken links detector on kubevirt.io that will be triggered by TravisCI in every PR/MR.
This is the status right now:
```
➜  kubevirt.github.io git:(master) rake
Building
bundle exec jekyll build
Configuration file: /home/jparrill/ownCloud/RedHat/RedHat_Engineering/kubevirt/repos/kubevirt.github.io/_config.yml
Source: /home/jparrill/ownCloud/RedHat/RedHat_Engineering/kubevirt/repos/kubevirt.github.io
Destination: /home/jparrill/ownCloud/RedHat/RedHat_Engineering/kubevirt/repos/kubevirt.github.io/_site
Incremental build: disabled. Enable with --incremental
Generating... 
Liquid Warning: Liquid syntax error (line 86): Expected end_of_string but found open_round in "{{ lookup('env','AWS_ACCESS_KEY') }}" in labs/ocp/appendices.md
Liquid Warning: Liquid syntax …
```
> Activating tests for CI/CD validation on PR/MR

- pages/ec2.md
- pages/gcp.md
This makes the title consistent with the homepage where the button
states "KubeVirt on X, Try It!".
Fixes: https://github.com/kubevirt/kubevirt.github.io/issues/126
> Change title to "Try KubeVirt on X" from "Easy Install using X"

- pages/ec2.md
- pages/gcp.md
Weave Net is installed by kubevirt-ansible as the CNI for pod to pod
communications. kubevirt-ansible reserves the 172.30.0.0/16 CIDR for
Weave's IP allocation range.
Both EC2 and GCP pages are updated to include information about where
conflicts could occur during instance setup.
Fixes issue https://github.com/kubevirt/kubevirt.github.io/issues/138
> Include warning about possible conflicts with Weave IP allocation

- _data/labs_toc.yml
- _layouts/kubernetes.html
Fixes the missing highlight functionality from the Labs sidebar when the active page is in view.
This PR fixes https://github.com/kubevirt/kubevirt.github.io/issues/115.
> add TOC for sidebar highlighting

- labs/kubernetes/lab6.md
- labs/kubernetes/lab7.md
- labs/manifests/pvc_fedora.yml
* removed section in lab6 on using virtctl to use vnc. 
* updated CDI lab to latest version, 1.2.0
* updated pvc_fedora.yml to use updated annotation
* improved CDI lab instructions on what to do if import fails and the need to monitor VM boot to know when they can login via ssh
* updated URL to fedora image. The fedora mirror returned 404 on EC2 instance.
> Kubernetes labs update 

- pages/ec2.md
- pages/gcp.md
Published new AWS and GCP images to fix weave-net conflict issue: https://github.com/kubevirt/kubevirt.github.io/issues/138
Updated EC2 page with new AMI ids.
Remove note about watching out for conflict in 172.30.0.0 IP range from
EC2 and GCP pages.
> New images published to fix weave-net conflict issue

- _data/labs_toc.yml
- labs/kubernetes/lab1.md
- labs/kubernetes/lab2.md
- pages/ec2.md
- pages/gcp.md
Renames lab6 to lab1 and lab7 to lab2 to avoid confusion as to where are
labs 1-5.
The original names came from how they were ordered in the OCP labs. The
Kubernetes labs are missing 1-5 because we don't guide users through
installation.
> Rename Kubernetes labs

- _data/labs_toc.yml
The proofer looks for generated files. Although the URLs resolve 
correctly without specifying the .html extention, the proofer is more 
strict.
> Add .html extension to urls to fix HTML-Proofer errors

- _data/labs_kubernetes_variables.yml
- labs/kubernetes/lab1.md
- labs/kubernetes/lab2.md
Various parts of lab commands are templated so that we can use the
variables that feed into the templates as a source. The variables
are stored in a yaml file.
We can then use this yaml file in cloud-image-builder to create tests
for the labs. The cloud-image-builder tests can then test against
the same manifests and commands that the users go through in
completing the labs.
> Template labs commands into variables

- _posts/2018-11-26-kubevirt-at-kubecon-na.markdown
Announce/highlight KubeCon NA 2018 sessions related to KubeVirt and the
contributors meetup.
> Blog: Announce KubeCon NA 2018 sessions

- _includes/scriptlets/lab1/01_get_vm_manifest.sh
- _includes/scriptlets/lab1/02_create_testvm.sh
- _includes/scriptlets/lab2/02_get_cdi_controller_manifest.sh
- labs/manifests/vm.yaml
- labs/manifests/vm1_pvc.yml
* Updated apiVersion and volume naming in vm1_pvc.yml.
* Creates a copy of the demo/vm.yaml file here so that new changes to the demo vm doesn't break users who are using an older version of KubeVirt.
* Updates CDI to v1.5.0.
> KubeVirt v0.13.0 updates

- _includes/scriptlets/get_kubevirt/02_deploy_kubevirt.sh
This change updates the deploy section of get_kubevirt to use the correct variable created in the previous step.
> Correct variable in deploy script

- Gemfile
- _config.yml
- pages/quickstart_minikube.md
* Add redirect-from to quickstart_minikube.md
* Add jekyll-redirect-from to both jekyll config and Gemfile
* Fix #205
> issue205: Add redirect for get_kubevirt

- _posts/2018-06-21-Run-Istio-with-kubevirt.markdown
- pages/ec2.md
The new images also fixed first-boot.sh issue mentioned in 
https://github.com/kubevirt/cloud-image-builder/issues/107
> Update AWS images to KubeVirt v0.16.1

- blogs/index.html
They're not right now and it's expected ui on a blog.
> Have blog titles be links in /blogs/

- _sass/_typography.scss
#219 caused the font size of headers to be smaller (applying the link's settings).
Now that they contain links, this should specify their correct size again.
> Fix font size on blog post headers

- _includes/scriptlets/lab2/05_view_cdi_pod_status.sh
Updating script to look at the `cdi` namespace. This script gets used at various places including the CI tests for cloud-image-builder.
> cdi is now in its own namespace apparently

- Gemfile
- Rakefile
In order to solve a future problem with Prow platform testing:
```
$ bundle exec rake
Building
bundle exec jekyll build
`/` is not writable.
Bundler will use `/tmp/bundler/home/unknown' as your home directory temporarily.
Configuration file: /kubevirt/_config.yml
Source: /kubevirt
Destination: /kubevirt/_site
Incremental build: disabled. Enable with --incremental
Generating... 
Jekyll Feed: Generating feed for posts
Liquid Warning: Liquid syntax error (line 112): [:dot, "."] is not a valid expression in "{{.status.podIP}}" in /kubevirt/_posts/2018-10-03-KubeVirt-Network-Rehash.markdown
Liquid Warning: Liquid syntax error (line 198): [:dot, "."] is not a valid expression in "{{.status.podIP}}" in …
```
> Fix: Future test problems on Prow

- labs/manifests/pvc_fedora.yml
AWS seems to be currently having issues resolving "fedora.mirror.constant.com" so I'm taking this opportunity to change the mirror to something GCP and AWS can currently resolve and to bump the version number to 30 to track a later release (I think 28 was probably just the latest when this file was last updated).
This resolves a critical issue and frankly makes all your wildest dreams come true.
**Does this PR fix any issue?** 
No Github issue, no.
N/A
> Updating .qcow image URL to work around intermittent DNS issues on AWS

- GUIDELINES.md
Reverts kubevirt/kubevirt.github.io#288
As the failure was with GHP, restoring article to original content
> Revert "Replace links as it was failing with GitHub Pages build"

- pages/gcp.md
**What this PR does / why we need it**
There's a reference to EC2 in the page about GCP as reported in kubevirt/cloud-image-builder#108
> Fixes kubevirt/cloud-image-builder#108
> Remove EC2 reference from GCP page

- _includes/head.html
Added go-import meta data for new kubevirt/client-go repository
> Added go-import meta data for new kubevirt/client-go repository

- pages/client-go.md
Follow up to https://github.com/kubevirt/kubevirt.github.io/pull/296, forgot to create a page from which the new import will be queried by go...
> Added page needed for go import of kubevirt/client-go.

- labs/manifests/pvc_fedora.yml
…kube environments
Need to fix the issue #350 so that hostpath is used as storageClass even there are more than one default storageClass. Also the PVC size has been decreased to 4Gi so that Fedora30 can be imported in Minikube environments with more than 4Gi of memory configured.
> Fixes #350
I did not tested on cloud providers but on minikube
Validated on:
> #issue 350 - Added storageclass hostpath to pvc and decreased the size to also work on minikube

- labs/manifests/pvc_fedora.yml
… range
Modifies pvc_fedora so the image imported is formatted as raw instead of qcow2
> Fixes #
Solves issue #373 
Must be reviewed in minikube, AWS and GCP that lab2 can be finished successfully
> Cloud image changed from qcow2 to raw since Fedora CDN not supporting range

- labs/kubernetes/lab2.md
Clarifies the difference ssh'ing to a VMI from a node inside the SDN and a node outside the SDN (nodeport)
> Fixes #
#362 and #361 
I tried to differentiate the logic between connecting using ssh inside the K8S cluster and connecting to ssh using nodeport. Tried to avoid as much as possible this is how must be done in cloud providers and this is how needs to be done in minikube. 
Actually, the PR instead of differentiate between cloud providers and minikube , it differentiates between ssh inside the sdn and …
> Clarified access to vm1 in lab2

- labs/manifests/storage-setup.yml
Alleviate the resources needed to import fedora30 cloud image when running minikube. Basically, this PR makes minikube and all cloud providers to store pv/pvs /var/lib/minikube. 
This only really applies to minikube since storage setup configuration was storing the pv in memory (tmpfs) while importing the cloud image. This was causing the VM to exhaust their resources when importing regular cloud images (~4G)
In order to keep only one storage class yaml file for the labs and same set of instructions I just modified the storage-setup.yml replacing the PV local path to a path where minikube uses persistent disk. Check [1](https://kubernetes.io/docs/setup/learning-environment/minikube/#persistent-volum …
> Modified storage class PV path to /var/lib/minikube in all labs

- README.md
Run local jekyll environment when testing the website using podman instead of docker. Podman is the default container engine in many distros. 
> Fixes #
Assess if it makes sense to show both docker & podman in the README file. IMHO one it is enough.
> Use podman instead of docker to run local jekyll

- _layouts/post.html
Some articles doesn't have comments: true so end users cannot comment on them
> Fixes #
This enables by default comments unless blocked on individual articles
> Enable comments by default on articles

- _includes/scriptlets/quickstart_kind/02_setenv_version.sh
- _includes/scriptlets/quickstart_minikube/04_setenv_version.sh
`cut -d- -f1` will set the version to a potentially nonexistent one.
Using `grep -v -- -` instead will ignore dash-ed versions (i.e. RCs).
Signed-off-by: Jed Lejosne <jlejosne@redhat.com>
> Omit versions that include a dash when computing $KUBEVIRT_VERSION

- pages/community.html
We use Slack more than IRC nowadays. The README in the main kubevirt
repo was recently updated (in kubevirt/kubevirt#3024) to replace the
reference to `#kubevirt` on freenode with one to `#virtualization`
on Kubernetes Slack. This change updates the website to match that.
> Fixes #
> Point chat to Slack instead of IRC

- pages/community.html
A missing `n` slipped by in #478 - this fixes it.
> Fixes #
> Typo in slack channel name

- _includes/footer.html
#472 added a link to Slack in the footer. This updates the link to point directly to the #virtualization channel instead of the generic Kubernetes Slack.
> Fixes #
> Update slack link to point to the #virtualization channel

- _config.yml
Disables HTML as the default code for formatting to avoid issues when files are included and proper language ink is not defined:
vs actual:
> Disable default language for code formatter

- Rakefile
Attempt to ignore youtube links with link checker because there are repetitive 429 errors while the video can be still accessed and causes false positives
> Ignore youtube links

- .pre-commit-config.yaml
- scripts/update_changelog.sh
Precommit does validate commits formatting of added files for several aspects:
- markdown recommendations
- python recommendations
- others
This commit addjusts formatting configuration for shell files in the repo (like update_changelog) by using shfmt tool
> Adjust precommit configuration for code files

- Rakefile
Ignore 429 errors which should be undefined as either failed or succeed instead of failing
> Ignore 429 errors with html-proofer

- LICENSE
The LICENSE file in the website was inherited verbatim from the generator tool that is used to create the site (jekyll). However, the content in the site comes from KubeVirt contributors. As the copyright
note is about the web site content and not the tool used to generate it, it should reflect this.
> Fixes #
> Update the copyright line in the license file

- _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
This PR fixes the issue found in some code blocks in the blogpost "KubeVirt: installing Microsoft Windows from an ISO", the code blocks are not rendered properly and they are being shown as markdown code instead of html code.
**Special notes for your reviewer**: check if the code blocks after the sentence "To upload data to the cluster, the cdi-uploadproxy service must be accessible from outside the cluster. In a production environment, this probably involves setting up an Ingress or a LoadBalancer Service." are rendered properly or you still can see the ```sh annotations.
> Some issue found showing some code blocks in the "KubeVirt: installing Microsoft Windows from an ISO" blogpost

- .pre-commit-config.yaml
- .yaspeller.json
Yaspeller got a PR merged so that it can be used directly.
This moves configuration to .yaspellerrc and makes pre-commit to check only markdown files in the commit
> Fixes #
> Point to yaspeller repository for checking spelling via pre-commit

- _posts/2018-06-20-Hello-KubeVirt-on-Minikube.markdown
- pages/quickstart_minikube.md
The minikube documentation for the kvm2 driver changed location, causing broken links.
This fixes a couple of references to it with their new location.
> Fixes #
> Fix link to minikube docs

- _posts/2019-10-31-prow-jobs-for-kubevirt.markdown
kubevirt/project-infra#408 reorganized the project-infra repo a bit.
There's a blog post that contains links to that repo. This PR fixes these links.
It fixes tests that are now failing for all PRs.
> Fixes #
> Fix link to prow job definition

- .yaspeller.json
- labs/kubernetes/lab3.md
A link to the user guide in lab3 still had the format prior to the conversion to markdown, which resulted in a broken link.
This corrects the link to the new structure of the user guide.
Fixes #568 
There's also a one-line correction in the spell checker dictionary to remove a duplicate entry, not worth a separate PR
> Fix link to the user guide in lab3

- pages/quickstart_kind.md
Signed-off-by: Marcin Franczyk <marcin0franczyk@gmail.com>
It clarifies the usage of the nested virtualization option for Kind quick-start
> clarify nested virtualization option for kind quick-start

- _posts/2018-10-03-KubeVirt-Network-Rehash.markdown
- pages/blogs/date.md
This PR fixes the Liquid syntax errors around page building, due to Jekyll trying to render/read code blocks that are not used in the creation of the site. Use the `{% raw %} and {% endraw %}` escapes to force Jekyll to ignore the code block.
For future pages with this issue, the `{% raw %} and {% endraw %}` must be placed around any `{% for %}` and `{% endfor %}` expressions, or else they will fail with the error _Unknown tag 'endfor'_.
**Does this PR fix any issue?** 
> Fixes #598
Run `Jekyll Build` to see that the `Liquid Warning: Liquid syntax error...` errors are no longer present.
> Fix Liquid syntax errors

- .travis.yml
Use a newer Ruby version in travis-ci
> Use a newer Ruby version in travis-ci

- _posts/2019-06-04-Kubevirt-vagrant-provider.markdown
HTMLproofer running in Netlify is failing because this url is now a redirect.  HTMLproofer runs successfully both locally on the metal and within the container.  Hopefully this fixes the problem so pull/614 can proceed.
> Update to Vagrant Getting-started guide url to fix HTMLproofer failures.

- pages/quickstart_minikube.md
Signed-off-by: Chris Callegari <mazzystr@gmail.com>
Removing mention of linux-86_64 since it's removed from builds
> Remove linux-x86_64 from KubeVirt on minikube quickstart guide

- _posts/2018-05-16-KubeVirt-API-Access-Control.markdown
- _posts/2018-11-16-new-volume-types.markdown
- labs/kubernetes/lab1.md
This should fix...
1) Pages with links to user-guide throwing 404 - Not Found pages
2) These pages also reference registryDisk which was migrated to containerDisk
> Update to fix links and containerdisk

- .yaspeller.json
- _includes/head.html
- pages/controller-lifecycle-operator-sdk.md
This PR adds go import redirect for controller-lifecycle-operator-sdk module.
Signed-off-by: Jakub Dzon <jdzon@redhat.com>
> Adds controller-lifecycle-operator-sdk meta tag to support vanity import

- README.md
- pages/alicloud.md
- pages/cloud.md
- pages/ec2.md
- pages/gcp.md
The recent change in #612 moved the /try it on clouds/ page from `cloud` to `quickstart_cloud`. There were some pages linking to `cloud`. This PR updates redirects so that they point to `quickstart_cloud` instead, and adds a redirect from `cloud` to `quickstart_cloud` for any potential external links pointing there.
Also it updates the `README` instructions about link checking to match what's defined in the prow job for link checks.
> Fixes #
> Fix redirection links in cloud quickstart pages

- _posts/2018-05-16-KubeVirt-API-Access-Control.markdown
- _posts/2018-06-21-Run-Istio-with-kubevirt.markdown
- _posts/2018-09-11-KubeVirt-Memory-Overcommit.markdown
- _posts/2018-09-12-attaching-to-multiple-networks.markdown
- _posts/2018-11-16-new-volume-types.markdown
- _posts/2019-06-04-Kubevirt-vagrant-provider.markdown
- assets/2019-02-22-federated-kubevirt/federated_vm.yaml
- labs/manifests/vm.yaml
Our  documentation is pointing to containerDisk images that are no longer maintained. A year or so ago we changed the name of the containerDisk feature from registryDisk to containerDisk. With that change, our demo image names changed from *-registry-disk-demo to *-container-disk-demo.
> Update our documentation to point to the container disk images we currently support

- _posts/2019-12-17-KubeVirt_UI_options.md
A blog post from last year contains some links to octant documentation that don't work anymore.
This PR replaces them with what seems to be their updated versions.
> Fixes #
> Fix broken links in a blog post

- js/video.popup.js
This change makes the "KubeVirt overview" video in the home page start to play as soon as it pops up.
Currently to view the video you need 2 clicks. With that, it's just 1 click.
> Fixes #
> Make the popup video auto-play when open

- labs/manifests/pvc_fedora.yml
Fedora 30 images are not in the mirrors any more. 
This PR updates the link to the Fedora cloud image to the latest version (33).
> Fixes #
> lab2: update the version of the Fedora image

- Rakefile
Link checking on Katacoda is [failing with 403 Forbidden](https://travis-ci.org/github/kubevirt/kubevirt.github.io/builds/747946963#L425).
Testing with curl suggests that a custom user agent prevents this:
```
$ curl -I https://www.katacoda.com/kubevirt/scenarios/kubevirt-101
HTTP/1.1 403 Forbidden
Date: Mon, 07 Dec 2020 09:30:30 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Set-Cookie: __cfduid=de2cf3a12516943dfd2830c767705da391607333430; expires=Wed, 06-Jan-21 09:30:30 GMT; path=/; domain=.katacoda.com; HttpOnly; SameSite=Lax
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
X-Katacoda-Host: web
X-Katacoda-Region: europe
Set-Cookie: …
```
> Add custom user agent to HTMLProofer

- pages/summit.md
This removes the part of the landing page with instructions about the process to submit a proposal.
The summit was accepting proposals until end of last week, so these are obsolete now.
> Fixes #
> Remove the CfP from the summit page

- pages/summit.md
The URL used for the registration takes you straight to register; the first thing you see when clicking that link is a Linux Foundation login page (unless you were already logged in to the LF).
This changes the URL to the more friendly event page, which provides some information.
> Fixes #
> Update the summit event link to the info page

- _posts/2018-04-25-KubeVirt-Network-Deep-Dive.markdown
- _posts/2018-05-08-KubeVirt-objects.markdown
- _posts/2018-05-16-KubeVirt-API-Access-Control.markdown
- _posts/2018-11-16-new-volume-types.markdown
- _posts/2019-01-22-An-overview-to-KubeVirt-metrics.markdown
- _posts/2019-03-14-More-about-Kubevirt-metrics.markdown
- _posts/2019-07-29-How-To-Import-VM-into-Kubevirt.markdown
- _posts/2019-07-30-NodeDrain-KubeVirt.markdown
- _posts/2019-10-23-KubeVirt_k8s_crio_from_scratch_installing_KubeVirt.md
- _posts/2019-10-30-KubeVirt_storage_rook_ceph.md
- _posts/2019-11-28-KubeVirt_basic_operations_video.md
- _posts/2019-12-04-KubeVirt_lab1_use_kubevirt.md
- _posts/2019-12-10-KubeVirt_lab2_experiment_with_cdi.md
- _posts/2020-01-21-KubeVirt_lab3_upgrade.md
- _posts/2020-01-24-OKD-web-console-install.md
- _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
- _posts/2020-02-25-Advanced-scheduling-with-affinity-rules.md
- _posts/2020-03-22-Live-migration.md
- _posts/2020-05-12-KubeVirt-VM-Image-Usage-Patterns.md
- _posts/2020-05-25-SELinux-from-basics-to-KubeVirt.md
- _posts/2020-06-22-win_workload_in_k8s.md
- _posts/2020-12-10-Customizing-images-for-containerized-vms.md
- labs/kubernetes/lab1.md
- labs/kubernetes/lab3.md
**Does this PR fix any issue?**
This fixes website content containing broken links to user-guide as well as long time standing broken selectors.
Near two broken links I found two instances of emotionally charged words.  They're one word changes.  More info [here](https://www.redhat.com/en/blog/update-red-hats-conscious-language-efforts) on why we need to be diligent about the choice of words we use.
> Fix user guide links

- labs/manifests/pvc_fedora.yml
The virtual size of the Fedora cloud image is 4 GiB:
```console
$ qemu-img info https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.qcow2
image: https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.qcow2
file format: qcow2
virtual size: 4 GiB (4294967296 bytes)
disk size: unavailable
cluster_size: 65536
Format specific information:
compat: 0.10
compression type: zlib
refcount bits: 16
```
and this causes the image importer to fail with the currently requested 4GiB PVC size (need to account for the small overhead):
```
E0223 08:15:08.906080       1 data-processor.go:238] Virtual image size 4294967296 is larger than available …
```
> Increase the PVC size to host the Fedora image

- _posts/2021-04-30-intel-vgpu-kubevirt.md
Fixes an oversight in the blog post where I left the "example" description for the blog post in place. Current description does not look good on blog post listing page.
> Update description field for 2021-04-30-intel-vgpu-kubevirt blog post

- README.md
This PR fixes a typo in the Readme, and also updates the section on running tests. The instructions say to run "test_links" and "test_spelling", however the make commands are "check_links" and "check_spelling".  Commands were tested to ensure that they work.
Signed-off-by: Mark DeNeve <markd@xphyr.net>
> typo fix and updates to test work section of readme

- _posts/2021-07-16-kubevirt-api-auth.md
The following is a new blog post for the kubevirt.io blog. It is based on some work I did for a customer who was asking about how to handle authentication when using the client-go library. Post is designed to show how the client-go library can leverage both KUBECONFIG as well as detect it is running inside k8s and leverage the auth token of the service account it is running as. It also discusses the use of k8s service accounts, and how to create them.
Use of a service account and token is based on _my_ understanding of the best way to handle k8s authentication from an application. Please review and let me know if there is a better or more secure way to handle this sort of request.
Signed-off-by: Mark DeNeve …
> new post on using client-go library and kubernetes authentication

- Makefile
This PR adds the `check_lint` markdown target to the Makefile in order lint all of the `*.md` files in the repository.
> Fixes #652 
@mazzystr Tried to pick up some of the notes from #719. Figured this would be a good starting point. The current `LINT_IMAGE` is just a stand-in for now until https://github.com/igorshubovych/markdownlint-cli/pull/208 (hopefully) gets merged.
> Add check_lint markdown target

- Makefile
Added the ability for the Makefile to automatically check SELinux enforcing status and set the SELINUX_ENABLED make variable accordingly.
New test only takes effect if SELINUX_ENABLED is not defined already, so it will not override a forced setting.
> Added automatic detection of SELinux

- _posts/2018-04-25-KubeVirt-Network-Deep-Dive.markdown
- _posts/2018-06-07-Non-Dockerized-Build.markdown
- _posts/2018-07-03-Unit-Test-Howto.markdown
- _posts/2018-08-08-kubevirtci.markdown
- _posts/2018-09-12-attaching-to-multiple-networks.markdown
- _posts/2018-10-09-containerized-data-importer.markdown
- _posts/2019-04-17-Hyper-Converged-Operator.markdown
- _posts/2019-07-08-kubevirt-with-ansible-part-2.markdown
- _posts/2019-07-29-How-To-Import-VM-into-Kubevirt.markdown
- _posts/2019-08-01-KubeVirt-CR-Condition-Types-Rename.markdown
- _posts/2020-01-24-OKD-web-console-install.md
- _posts/2020-02-14-KubeVirt-installing_Microsoft_Windows_from_an_iso.md
- _posts/2020-05-12-KubeVirt-VM-Image-Usage-Patterns.md
- _posts/2020-12-10-Customizing-images-for-containerized-vms.md
- _posts/2020-12-10-Monitoring-KubeVirt-VMs-from-the-inside.md
- _posts/releases/2017-11-07-Kube-Virt-v004.markdown
- _posts/releases/2017-12-08-Kube-Virt-v010.markdown
- _posts/releases/2018-01-05-Kube-Virt-v020.markdown
Signed-off-by: Tyler Auerbeck <tauerbec@redhat.com>
This removes references to KubeVirt `master` branches on repositories that have switched to use `main`. There a handful of repositories that haven't made the switch yet, so they were not able to be updated. This list includes:
- kubevirt-ansible
- vm-import-operator
- cloud-image-builder
- community
- ansible-kubevirt-modules
- common-templates
- kubevirt-tutorial
Begin to address #726 (but not finished)
> Update KubeVirt refs master -> main

- _posts/2021-09-21-Importing-EC2-to-KubeVirt.md
This blog post outlines the basics behind how to import AWS AMIs into a kubevirt cluster and execute kubevirt VMs using those imported AMIs.
> Blog post: Import AWS AMIs as KubeVirt Golden Images

- Makefile
- Rakefile
- netlify.toml
* Created netlify.toml so that Netlify build config can be controlled via file in git
* Removed 'links:test_external', 'links:test_internal' from Rakefile so that duplicate link checking no longer occurs
* It appears check_selectors is broken again.  Moved the whole script to it's own Makefile target so it doesn't interfere with normal link checking.
> Fixes #817
> Fixed #817, Moving Netlify configuration to local toml

- GUIDELINES.md
- Makefile
- README.md
- _includes/quickstarts/kubectl.md
- package.json
Some instances of "master" we missed in the website docs and Makefile after renaming the default branch to main.
> Replaced old master branch name

- pages/summit.md
Adds in the schedule of selected sessions for the Kubevirt Summit.
Attn @fabiand @rmohr
> Add Summit Schedule.

- _posts/2022-01-24-KubeVirt-Summit-2022.md
Creates blog post to ensure summit is in our news feed.
refers to https://github.com/kubevirt/kubevirt.github.io/pull/824
> Adding post to link to and socialize the second kubevirt summit

- _includes/head.html
- pages/node-maintenance-operator.md
Add go import config for Node Maintenance Operator for enabling `go get kubevirt.io/node-maintenance-operator`
> Add go import config for Node Maintenance Operator

- _posts/2022-04-03-Virtual-Machines-with-MetalLB.markdown
> Load-balancer for virtual machines on bare metal Kubernetes clusters

- _includes/scriptlets/lab2/03_deploy_cdi_operator.sh
While doing the KubeVirt Labs I noticed that `VERSION` was not set using the snippet to install the CDI. Github is responding with a HTTP redirect, so the latest version needs to be grabbed from the location header instead of the response body.
> Fix getting the latest CDI version in lab2

- pages/quickstart_minikube.md
**What this PR does / why we need it**
Recent changes in minikube have broken our quickstart in two places:
- https://github.com/kubernetes/minikube/issues/15918 
- https://github.com/kubevirt/kubevirt.github.io/issues/859
A documentation fix was found for #859 where we add a CNI to make masquerade VMs work.
An issue has been filed against minikube because a missing curl command has broken the kubevirt addon.
> Update minikube instructions with recent changes

- _posts/2023-05-31-OVN-kubernetes-secondary-networks-localnet.md
[This PR](https://github.com/ovn-org/ovn-kubernetes/pull/3609) reacts to changes in the ovn-kubernetes repo, where the `_br-localnet` suffix was removed from the mapping configuration.
Thus, we need to adjust the existing blog post, otherwise the provided instructions will not provide a working scenario.
We also clarify the existing command to retrieve the name of the bridge where the "gateway" IP must be set only works for podman.
> Fixes #
> Fix localnet blog

- _includes/scriptlets/lab2/06_create_fedora_cloud_instance.sh
- labs/kubernetes/lab2.md
The CDI lab in kubevirt.io contains out-of-date processes and information, to the point where it recommends the creation of a PVC with import annotations instead of a DataVolume. The given example simply doesn't work with the latest CDI version.
Though we plan to eventually change the way CDI works with DataVolumes (check https://github.com/kubevirt/containerized-data-importer/pull/2752 for more information), the lab should at least provide a working example so users can test CDI's latest versions.
With the adoption of populators this process will require an update again soon, but since users have been reporting issues with the current lab (https://github.com/kubevirt/containerized-data-importer/issues/2830 or …
> Update CDI lab to match the current behavior

- _posts/2023-09-05-Managing-KubeVirt-VMs-with-Ansible.md
This post explains how to manage KubeVirt VMs with the kubevirt.core Ansible collection.
Note: YouTube video still needs to be uploaded and link changed in post.
> blog: Managing KubeVirt VMs with Ansible

- pages/quickstart_cloud.md
- pages/quickstart_kind.md
- pages/quickstart_minikube.md
Replace complicated multi-command pipeline to get latest stable version string with an easy curl in our quickstart documentation.
Fixes #891 
> Replacing complicated latest version commands with simple curl

- _includes/head.html
Add go-import to import containerdisks via kubevirt.io domain.
> Add go-import containerdisks

- _posts/2023-09-06-KubeVirt-on-autoscaling-nodes.md
This ensures that the tags we set in the node group is also copid over to the underlying autoscaling group which is what the cluster autoscaler will look at for determining which node group to scale up.
This adds a missing line in a code block.
> Add propagateASGTags to code block

- _includes/head.html
Added go module redirect for `kubevirt.io/vm-console-proxy` to be consistent with other kubevirt projects.
> Add go-import for kubevirt.io/vm-console-proxy project

- pages/quickstart_cloud.md
- pages/quickstart_kind.md
- pages/quickstart_minikube.md
This PR fixes the improper interpolation of the "VERSION" variable within the URL string in the kubectl create command. This is because the curly braces {} are not being interpreted correctly in the URL as when they are pasted in other shells like `zsh`, escape is inserted around `{` & `}`.
To fix this, we need to use double quotes for the URL string in the kubectl create command.
> Fixes #934
> Fix shell's expansion of `VERSION` in deploy command

- labs/kubernetes/lab1.md
- pages/quickstart_kind.md
> Fix quickstart_kind and use kubevirt lab

- .pre-commit-config.yaml
- _posts/2025-02-26-Hardening-VMIM.md
This describes the hardening of VMIM RBAC proposed in https://github.com/kubevirt/community/pull/377 and implemented with https://github.com/kubevirt/kubevirt/pull/13497
This is not an API change but hardening according to the principle of least privilege (PoLP).
> New blog for VMIM RBAC hardening
